import "./globals.css";

export const metadata = {
  title: "Gusto e Passione",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="m-5 lg:mx-40 lg:my-20">{children}</body>
    </html>
  );
}
