import { RedHat } from "@/utils/fonts";
import "./globals.css";

export const metadata = {
  title: "Dessert Order",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={RedHat}>{children}</body>
    </html>
  );
}
